repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Use the latest stable version of black
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # Use the latest version of ruff-pre-commit
    hooks:
      - id: ruff
        args: ["--fix"]