apiVersion: v1
kind: PersistentVolume
metadata:
  name: vector-store-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/vector-store
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vector-store-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi